### ISSUE TITLE
revision-b tag was moved

### ISSUE THREAD

**Issue by bgilbert** [svoisen/bluenumi#3]
It's not safe to move a Git tag to point to a different commit, because `git pull` will not refresh existing tags.  You should treat a public tag as immutable, the same as a public commit.

Since there are two `revision-b` tags in the wild, that name is now permanently ambiguous.  The best thing would be to delete it and recreate it with a different name.

**Comment by svoisen** [comment]
No idea anyone was even bothering to clone this project :)

Fixed and renamed rev-b.
